[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "About"
  pageRef = "about"
  weight = 30

[[main]]
  name = "Ear Trainer"
  url = "/apps/piano-interval-trainer/"
  weight = 40
